/* Problem 2: Even Fibonacci numbers

   Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
   By starting with 1 and 2, the first 10 terms will be:
   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

   By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
   find the sum of the even-valued terms. */


function find_fibonacci(){
  var a = 1, b = 0, c = [], temp;

  while (a < 4000001){
    temp = a;
    a = a + b;
    b = temp;
    c.push(a);
  }
  c.pop();
  console.log(c);
  find_even_numbers(c)
}

function find_even_numbers(all_numbers){
  var even_numbers = [];
  for (var i = 0; i < all_numbers.length; i++) {
	  if (all_numbers[i]%2 === 0){
	    even_numbers.push(all_numbers[i]);
	  }
  }
  console.log(even_numbers);
}

find_fibonacci();